name: hichub
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - bedtools=2.30.0=hc088bd4_0
  - blas=2.3=openblas
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py37h89c1867_1
  - curl=7.71.1=he644dc0_8
  - krb5=1.17.2=h926e7f8_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=3_openblas
  - libcblas=3.9.0=3_openblas
  - libcurl=7.71.1=hcdd3856_8
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=7.5.0=h14aa051_18
  - libgfortran4=7.5.0=h14aa051_18
  - liblapack=3.9.0=3_openblas
  - liblapacke=3.9.0=3_openblas
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h6de172a_18
  - llvm-openmp=11.0.1=h4bd325d_0
  - ncurses=6.2=h58526e2_4
  - numpy=1.17.0=py37h99e49ec_0
  - numpy-base=1.17.0=py37h2f8d375_0
  - openssl=1.1.1j=h7f98852_0
  - pandas=1.2.2=py37hdc94413_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pybedtools=0.8.1=py37h8270d21_2
  - pysam=0.15.3=py37hda2845c_1
  - python=3.7.10=hffdb5ce_100_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd8ed1ab_0
  - readline=8.0=he28a2e2_2
  - setuptools=49.6.0=py37h89c1867_3
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.34.0=h74cdb3f_0
  - tk=8.6.10=h21135ba_1
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - pip:
    - backcall==0.2.0
    - decorator==4.4.2
    - hichub==0.0.7
    - ipython==7.21.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.16
    - ptyprocess==0.7.0
    - python-igraph==0.8.3
    - scipy==1.6.1
    - texttable==1.6.3
    - traitlets==5.0.5
    - wcwidth==0.2.5
prefix: /opt/miniconda2/envs/hichub

